version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ggeolmu_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Data/pgdata:/var/lib/postgresql/data



  manager:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: ggeolmu_manager_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      # n8n 내에서 파이썬 실행시 필요한 환경변수
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      # n8n 데이터 영구 보존용
      - ./Data/n8n_data:/home/node/.n8n
      # 파이썬 코드 접근용
      - ./Parser:/app/Parser
    depends_on:
      - postgres


