-- 012_create_technical_tables.sql
-- 기술적 분석 지표 (technical_indicators) 및 트레이딩 시그널 (trading_signals) 테이블 생성

CREATE TABLE IF NOT EXISTS public.technical_indicators (
    date DATE NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    market VARCHAR(20),
    ma1 NUMERIC,
    ma2 NUMERIC,
    ma3 NUMERIC,
    ma4 NUMERIC,
    ma5 NUMERIC,
    ma6 NUMERIC,
    ma7 NUMERIC,
    ma8 NUMERIC,
    ma9 NUMERIC,
    ma20 NUMERIC,
    ma50 NUMERIC,
    ma60 NUMERIC,
    ma90 NUMERIC,
    ma120 NUMERIC,
    ma200 NUMERIC,
    ma224 NUMERIC,
    close_diff_first NUMERIC,
    close_rate_first NUMERIC,
    currencyvolume NUMERIC,
    currencyvolume_ratio_ma20 NUMERIC,
    obv NUMERIC,
    mobv NUMERIC,
    deltamobv NUMERIC,
    rsi NUMERIC,
    rsi_signal NUMERIC,
    rsi_bulldiv NUMERIC,
    rsi_beardiv NUMERIC,
    rsi_hidden_bulldiv NUMERIC,
    rsi_hidden_beardiv NUMERIC,
    rsi_uptrend NUMERIC,
    rsi_downtrend NUMERIC,
    rsi2 NUMERIC,
    rsi_signal2 NUMERIC,
    rsi_bulldiv2 NUMERIC,
    rsi_beardiv2 NUMERIC,
    rsi_hidden_bulldiv2 NUMERIC,
    rsi_hidden_beardiv2 NUMERIC,
    rsi_uptrend2 NUMERIC,
    rsi_downtrend2 NUMERIC,
    rsi3 NUMERIC,
    rsi_signal3 NUMERIC,
    rsi_bulldiv3 NUMERIC,
    rsi_beardiv3 NUMERIC,
    rsi_hidden_bulldiv3 NUMERIC,
    rsi_hidden_beardiv3 NUMERIC,
    rsi_uptrend3 NUMERIC,
    rsi_downtrend3 NUMERIC,
    rsi4 NUMERIC,
    rsi_signal4 NUMERIC,
    rsi_bulldiv4 NUMERIC,
    rsi_beardiv4 NUMERIC,
    rsi_hidden_bulldiv4 NUMERIC,
    rsi_hidden_beardiv4 NUMERIC,
    rsi_uptrend4 NUMERIC,
    rsi_downtrend4 NUMERIC,
    rsi5 NUMERIC,
    rsi_signal5 NUMERIC,
    rsi_bulldiv5 NUMERIC,
    rsi_beardiv5 NUMERIC,
    rsi_hidden_bulldiv5 NUMERIC,
    rsi_hidden_beardiv5 NUMERIC,
    rsi_uptrend5 NUMERIC,
    rsi_downtrend5 NUMERIC,
    rsi6 NUMERIC,
    rsi_signal6 NUMERIC,
    rsi_bulldiv6 NUMERIC,
    rsi_beardiv6 NUMERIC,
    rsi_hidden_bulldiv6 NUMERIC,
    rsi_hidden_beardiv6 NUMERIC,
    rsi_uptrend6 NUMERIC,
    rsi_downtrend6 NUMERIC,
    rsi7 NUMERIC,
    rsi_signal7 NUMERIC,
    rsi_bulldiv7 NUMERIC,
    rsi_beardiv7 NUMERIC,
    rsi_hidden_bulldiv7 NUMERIC,
    rsi_hidden_beardiv7 NUMERIC,
    rsi_uptrend7 NUMERIC,
    rsi_downtrend7 NUMERIC,
    rsi8 NUMERIC,
    rsi_signal8 NUMERIC,
    rsi_bulldiv8 NUMERIC,
    rsi_beardiv8 NUMERIC,
    rsi_hidden_bulldiv8 NUMERIC,
    rsi_hidden_beardiv8 NUMERIC,
    rsi_uptrend8 NUMERIC,
    rsi_downtrend8 NUMERIC,
    rsi9 NUMERIC,
    rsi_signal9 NUMERIC,
    rsi_bulldiv9 NUMERIC,
    rsi_beardiv9 NUMERIC,
    rsi_hidden_bulldiv9 NUMERIC,
    rsi_hidden_beardiv9 NUMERIC,
    rsi_uptrend9 NUMERIC,
    rsi_downtrend9 NUMERIC,
    rsi_signal_sum NUMERIC,
    rsi_bulldiv_sum NUMERIC,
    rsi_beardiv_sum NUMERIC,
    rsi_hidden_bulldiv_sum NUMERIC,
    rsi_hidden_beardiv_sum NUMERIC,
    rsi_uptrend_sum NUMERIC,
    rsi_downtrend_sum NUMERIC,
    std20 NUMERIC,
    bollinger_high NUMERIC,
    bollinger_low NUMERIC,
    bb_width NUMERIC,
    cci NUMERIC,
    cci_signal NUMERIC,
    cci2 NUMERIC,
    cci_signal2 NUMERIC,
    cci3 NUMERIC,
    cci_signal3 NUMERIC,
    cci4 NUMERIC,
    cci_signal4 NUMERIC,
    cci5 NUMERIC,
    cci_signal5 NUMERIC,
    cci6 NUMERIC,
    cci_signal6 NUMERIC,
    cci7 NUMERIC,
    cci_signal7 NUMERIC,
    cci8 NUMERIC,
    cci_signal8 NUMERIC,
    cci9 NUMERIC,
    cci_signal9 NUMERIC,
    cci_signal_sum NUMERIC,
    macd NUMERIC,
    macd_base NUMERIC,
    macd_hist NUMERIC,
    macd_hist_vel NUMERIC,
    macd_hist_acc_pct NUMERIC,
    macd_positive NUMERIC,
    macd_signal NUMERIC,
    pdi NUMERIC,
    mdi NUMERIC,
    adx NUMERIC,
    mom10 NUMERIC,
    mom14 NUMERIC,
    mom25 NUMERIC,
    mom28 NUMERIC,
    mom10_signal NUMERIC,
    mom14_signal NUMERIC,
    mom25_signal NUMERIC,
    mom28_signal NUMERIC,
    high_watermark NUMERIC,
    mdd NUMERIC,
    is_pinbar NUMERIC,
    bb_fakeout NUMERIC,
    volume_climax NUMERIC,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (date, symbol)
);

CREATE TABLE IF NOT EXISTS public.trading_signals (
    date DATE NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    market VARCHAR(20),
    signal_type VARCHAR(50),
    signal_strength NUMERIC,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (date, symbol, signal_type)
);

CREATE INDEX IF NOT EXISTS idx_tech_indicators_symbol_date ON public.technical_indicators(symbol, date DESC);
CREATE INDEX IF NOT EXISTS idx_trading_signals_symbol_date ON public.trading_signals(symbol, date DESC);
